### pytorch の準備

In [1]:
import torch
torch.__version__

'1.12.0+cu116'

#### ネットワークの定義
3ノードの入力層（＋バイアス）と２ノードの中間層(+バイアス)と1ノードの出力層を持つMLP

In [2]:
import torch.nn as nn

fc1 = nn.Linear(3, 2)
fc2 = nn.Linear(2, 1)

重みとバイアスはランダムに初期化

In [3]:
fc1.weight

Parameter containing:
tensor([[-0.5463,  0.3739,  0.5586],
        [ 0.0690,  0.2250,  0.1600]], requires_grad=True)

In [4]:
fc2.weight

Parameter containing:
tensor([[-0.5027,  0.1213]], requires_grad=True)

In [5]:
fc1.bias

Parameter containing:
tensor([-0.0275, -0.3109], requires_grad=True)

In [6]:
fc2.bias

Parameter containing:
tensor([-0.3001], requires_grad=True)

入力値の定義

In [7]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
x

tensor([1., 2., 3.])

線形変換(入力層→中間層)：重みと入力変数の線形結合
- $u_{11} = w_{11} h_{01} + w_{12} h_{02} + w_{13} h_{03} + b_1$
- $u_{12} = w_{21} h_{01} + w_{22} h_{02} + w_{23} h_{03} + b_1$

In [8]:
u1 = fc1(x)
u1

tensor([1.8497, 0.6883], grad_fn=<AddBackward0>)

非線形変換：Relu（正規化線形関数）

- $h_{11} = \mathrm{max}(0, u_{11})$
- $h_{12} = \mathrm{max}(0, u_{12})$

In [9]:
import torch.nn.functional as F

h1 = F.relu(u1)
h1

tensor([1.8497, 0.6883], grad_fn=<ReluBackward0>)

線形変換（中間層→出力層）

In [10]:
y = fc2(h1)
y

tensor([-1.1465], grad_fn=<AddBackward0>)

PyTorchではネットワーク内での計算を行う際に、

`torch.nn (nn)`を用いる場合と、`torch.nn.functional (F)`を用いる場合の2通りの選択肢がある。

これらの違いは、以下
- `nn`：パラメタを持つ（`nn.Linear`は`weight`や`bias`のパラメタを持つ）
- `F`：パラメタを持たない（`F.relu`はパラメタを持たない）